name: CI

on:
    push:
        branches:
        - main

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build and run docker images
        run: docker-compose up --build

      - name: Run black
        run: docker-compose run formatter

      - name: Run flake8
        run: docker-compose run linter

      - name: Run tests
        run: docker-compose run tests