name: CI

on:
    push:
        branches:
        - main

jobs:
    format:
        name: Check format
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: psf/black@25.1.0
            with:
              options: "--check --verbose"
              src: "./"
              version: "25.1.0"

    lint:
        name: Run linter
        needs: [format]
        runs-on: ubuntu-latest
        steps:
          - name: Check out Git repository
            uses: actions/checkout@v3
          - name: Run flake8
            run: flake8 ./ --append-config=./.flake8 --verbose


